ignores_function_declarations: true
ignores_comments: true

disabled_rules:
  - variable_name
  - force_cast
  - trailing_newline
  - line_length


excluded:
  - Pods
  - Carthage
  - vendor
  - "**/Models/CoreData/*CoreDataProperties.swift"
